# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_owner',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='project',
            name='isPublic',
            field=models.BooleanField(default=False, verbose_name='Public?'),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
