# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20161005_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='isApproved',
            field=models.BooleanField(default=False, verbose_name='Approved?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isOther',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isResearcher',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isStudent',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isTeacher',
            field=models.BooleanField(default='False'),
        ),
    ]
